/* Account layout preview: no business data, payment requests, or authentication writes. */
(()=>{
 const app=document.querySelector('#app'),company=document.querySelector('#company'),documents=document.querySelector('#documents');
 let view='payments';
 const fileIcon='<svg viewBox="0 0 24 28" aria-hidden="true"><path d="M4 2h10l6 6v18H4zM14 2v7h6M8 14h8M8 19h8"/></svg>';
 const folderIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5h7l2 3h9v12H3z"/></svg>';
 const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 function title(name,summary=''){return '<div class="title-row"><h1>'+name+'<span class="company-tag">'+esc(company.value)+'</span></h1>'+summary+'</div>'}
 function emptyTable(headers,widths,heading,detail){return '<section class="panel"><div class="table-scroll"><table><colgroup>'+widths.map(width=>'<col style="width:'+width+'%">').join('')+'</colgroup><thead><tr>'+headers.map(([name,style])=>'<th class="'+(style||'')+'">'+name+'</th>').join('')+'</tr></thead><tbody><tr><td colspan="'+headers.length+'" class="empty-cell"><svg class="empty-icon" viewBox="0 0 32 32" aria-hidden="true"><path d="M8 3h11l6 6v20H8zM19 3v7h6M12 16h9M12 22h9"/></svg><div class="empty-title">'+heading+'</div><div class="empty-detail">'+detail+'</div></td></tr></tbody></table></div><div class="panel-footer"><span>'+esc(company.value)+' · Account Department</span><span>页面预览 · 尚未载入业务资料</span></div></section>'}
 function filters(history=false){return '<div class="filters"><input aria-label="Search purchase documents" placeholder="Search Our P.O. / PO ID / Supplier SO / INV / DO / CN"><select aria-label="Supplier"><option>All Suppliers</option></select>'+(history?'<select aria-label="Year"><option>All Years</option></select><select aria-label="Month"><option>All Months</option>'+Array.from({length:12},(_,i)=>'<option value="'+(i+1)+'">'+String(i+1).padStart(2,'0')+'</option>').join('')+'</select>':'<select aria-label="Payment status"><option>All Status</option><option>等待放款 / Waiting Payment</option><option>采购部催款 / Purchase Follow-up</option><option>已放款 / Paid</option></select>')+'<button class="files-entry" id="openDocuments">'+folderIcon+'Supplier Documents</button></div>'}
 function render(){
  document.querySelectorAll('nav [data-view]').forEach(button=>{const active=button.dataset.view===view;button.classList.toggle('active',active);active?button.setAttribute('aria-current','page'):button.removeAttribute('aria-current')});
  if(view==='payments'){
   const summary='<div class="summary" aria-label="Payment workload">'+['Waiting Payment','Purchase Follow-up','Files Pending','Ready to Archive'].map(label=>'<div class="summary-item"><span>'+label+'</span><b>—</b></div>').join('')+'</div>';
   app.innerHTML=title('Purchase Payments',summary)+filters()+emptyTable([['Date / By'],['Our P.O. / PO ID'],['Supplier'],['Amount / Balance','numeric'],['Terms / Due'],['Supplier No.'],['Status'],['Files','center'],['Entry','center']],[10,15,17,13,12,12,11,5,5],'采购付款工作台','采购员成功保存 P.O. 后，采购单将在这里进入待处理列表。<br>当前为页面预览，尚未接入真实采购单。')+'<p class="workflow-note">付款完成＋供应商必需文件核齐 → 财务确认完成 → History</p>';
  }else if(view==='history')app.innerHTML=title('History')+filters(true)+emptyTable([['Completed / By'],['Our P.O. / PO ID'],['Supplier'],['Amount','numeric'],['Supplier SO / INV / DO / CN'],['Files','center'],['Entry','center']],[12,18,20,13,25,6,6],'财务历史记录','可按我方 P.O.、PO ID、供应商单号、年份、月份和供应商查找。<br>当前尚未载入已完成的财务记录。');
  else if(view==='bank')app.innerHTML=title('Bank & Cash Flow')+'<p class="ledger-caption">银行余额与预计付款分别显示，余额保留登记时间。</p><div class="bank-summary">'+[['Recorded Balance','实际登记余额'],['Next 7 Days','预计付款'],['Next 30 Days','预计付款']].map(([name,detail])=>'<section class="bank-card"><span>'+name+'</span><b>—</b><small>'+detail+' · 尚未载入</small></section>').join('')+'</div>'+emptyTable([['Bank / Account'],['Currency'],['Recorded Balance','numeric'],['Updated / By'],['Expected Payments','numeric']],[25,10,20,25,20],'银行账户待设置','余额取得方式和登记规则待确认，当前不显示推测余额。');
  else {const debtor=view==='debtor';app.innerHTML=title(debtor?'Debtor':'Creditor')+'<div class="filters"><input aria-label="Search '+(debtor?'customer':'supplier')+'" placeholder="Search '+(debtor?'customer / Sales Invoice':'supplier / Supplier Invoice')+'"><select aria-label="Outstanding status"><option>All Outstanding</option><option>Overdue</option></select></div>'+emptyTable([[debtor?'Customer':'Supplier'],['Currency'],['Invoice Amount','numeric'],[debtor?'Received':'Paid','numeric'],['Balance','numeric'],['Due Date'],['Entry','center']],[25,10,15,15,15,14,6],debtor?'客户应收款':'供应商应付款',debtor?'根据客户 Sales Invoice 与收款记录显示；当前尚未载入。':'根据供应商账单、付款与已关联 CN 显示；当前尚未载入。');}
 }
 document.querySelector('#documentList').innerHTML=['Supplier SO','Supplier INV','Supplier DO','Supplier CN','Payment Proof','Other Documents'].map(name=>'<div class="document-row">'+fileIcon+'<div><strong>'+name+'</strong><small>文件尚未关联</small></div><button disabled>Download</button></div>').join('');
 document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.view){view=button.dataset.view;render()}else if(button.id==='openDocuments'){document.querySelector('#documentCompany').textContent=company.value;documents.showModal()}else if(['closeDocuments','documentsDone'].includes(button.id))documents.close()});
 company.addEventListener('change',()=>{documents.close();render()});render();
})();
