const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
function sourceFixture(records){let calls=0,field,ids;const source=fs.readFileSync(path.join(__dirname,'../../backend/masterCustomerNames.js'),'utf8').replace(/^import .*\r?$/gm,'').replace(/^export /gm,'');
 const wixData={query:collection=>{assert.equal(collection,'WixCustomers');calls++;const query={hasSome:(key,values)=>{field=key;ids=values;return query;},limit:()=>query,find:async()=>({items:records})};return query;}};
 const read=vm.runInNewContext(source+'\nreadMasterCustomerNames',{wixData,getSecret:async()=>'TEST_ONLY',timingSafeEqual:crypto.timingSafeEqual,Buffer,Set,Number,Object,JSON,Array,Error,String});
 return {read,calls:()=>calls,request:(customerIds,auth='Bearer TEST_ONLY')=>({headers:{authorization:auth},body:{json:async()=>({customerIds})}})};}
test('customer display lookup requires the existing Master credential before accessing customers',async()=>{const f=sourceFixture([]);assert.equal((await f.read(f.request(['CUS-TEST'],'Bearer WRONG'))).status,401);assert.equal(f.calls(),0);});
test('short name lookup returns only requested identity and name, preserving source data and omitting contact information',async()=>{const records=[{customerId:'CUS-TEST',customerShortName:'MASTER 02',email:'private',phone:'private'},{customerId:'CUS-OTHER',customerShortName:'OTHER'}],before=JSON.stringify(records),f=sourceFixture(records);const result=await f.read(f.request(['CUS-TEST']));assert.equal(result.status,200);assert.equal(JSON.stringify(result.body.customers),'[{"customerId":"CUS-TEST","shortName":"MASTER 02"}]');assert.equal(JSON.stringify(records),before);});
test('malformed IDs and duplicates do not query; missing or ambiguous customer never gets a guessed name',async()=>{for(const ids of [null,['CUS-TEST','CUS-TEST'],['../Staff'],Array(201).fill('CUS-TEST')]){const f=sourceFixture([]);assert.equal((await f.read(f.request(ids))).status,503);assert.equal(f.calls(),0);}for(const records of [[],[{customerId:'CUS-TEST'},{customerId:'CUS-TEST'}]])assert.equal((await sourceFixture(records).read(sourceFixture([]).request(['CUS-TEST']))).status,503);});
test('source HTTP patch preserves all existing routes and FX handler exactly',()=>{const current=fs.readFileSync(path.join(__dirname,'../../backend/http-functions.js'),'utf8').replace(/\r\n/g,'\n');const baseline=require('node:child_process').execFileSync('git',['show','1eb395a:backend/http-functions.js'],{cwd:path.join(__dirname,'../..'),encoding:'utf8'}).replace(/\r\n/g,'\n');const stripped=current.replace("import { readMasterCustomerNames } from 'backend/masterCustomerNames.js';\n",'').split('export async function post_masterCustomerNames(request) {')[0].trimEnd();assert.equal(stripped,baseline.trimEnd());});
test('Master names lookup follows staff authorization and requests only the visible PO customer identities; failure preserves orders',async()=>{
 const source=fs.readFileSync(path.join(__dirname,'../backend/purchaseOrders.web.js'),'utf8').replace(/^import .*\r?$/gm,'').replace(/^export /gm,''),rows=[{id:'PO',customerId:'CUS-TEST',customerName:'Full Company',amount:10,taskIds:['TASK']}];
 for(const fail of [false,true]){const calls=[];const read=vm.runInNewContext(source+'\ngetPurchaseOrders',{wixData:{},webMethod:(_permission,fn)=>fn,Permissions:{SiteMember:1},getPurchaseStaffContext:async()=>{calls.push('STAFF');return {};},createPurchaseOrderOperations:()=>({list:async()=>{calls.push('PO');return rows;}}),PURCHASE_COLLECTIONS:{},requestPurchaseDocument:()=>{},projectPurchaseWorkspace:()=>{},readCustomerShortNames:async ids=>{calls.push(Array.from(ids));if(fail)throw Error('Network error');return [{customerId:'CUS-TEST',shortName:'SHORT'}];},Set,Object,Array,Number,JSON,Error});
 const before=JSON.stringify(rows),result=await read('NCT');assert.deepEqual(calls,['STAFF','PO',['CUS-TEST']]);assert.equal(result.orders[0].customerName,fail?'Full Company':'SHORT');assert.equal(result.orders[0].amount,10);assert.equal(JSON.stringify(rows),before);assert.equal(Boolean(result.customerNamesError),fail);}
});
