const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),path=require('node:path');
function service(){const files=new Map();let calls=0;const secret='test-only-not-a-live-secret-123456789';
 const context={PropertiesService:{getScriptProperties:()=>({getProperty:()=>secret})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},
 Utilities:{base64Decode:s=>[...Buffer.from(s,'base64')],computeDigest:(_,bytes)=>[...crypto.createHash('sha256').update(Buffer.from(bytes)).digest()],DigestAlgorithm:{SHA_256:'sha'},newBlob:(bytes,mime,name)=>({bytes,mime,name})},
 LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Drive:{Files:{generateIds:()=>{calls++;return {ids:['generated_file_id_123']};},create:(metadata,blob)=>{calls++;if(files.has(metadata.id))throw Error('conflict');const file={...metadata,size:blob.bytes.length,webViewLink:'https://drive.google.com/file/d/'+metadata.id+'/view'};files.set(metadata.id,file);return file;},get:id=>{calls++;if(!files.has(id))throw Error('not found');return files.get(id);}}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../apps-script/purchase-documents/Code.gs'),'utf8'),context);
 const bytes=Buffer.from('%PDF-1.4\ntest fixture');return {files,calls:()=>calls,run:input=>context.doPost({postData:{contents:JSON.stringify(input)}}),input:{token:secret,action:'UPLOAD',company:'NCT',fileId:'generated_file_id_123',poId:'a'.repeat(32),sha256:crypto.createHash('sha256').update(bytes).digest('hex'),base64:bytes.toString('base64'),name:'2026-10-11 SUP INV 001.pdf',type:'INV'}};
}
test('unauthorized or invalid-company upload cannot call Google Drive',()=>{const f=service();assert.equal(f.run({...f.input,token:'wrong'}).error,'NOT_AUTHORIZED');assert.equal(f.run({...f.input,company:'OTHER'}).error,'INVALID_COMPANY');assert.equal(f.calls(),0);});
test('upload fixes company folder and retry reuses the generated file ID without a duplicate',()=>{const f=service();assert.equal(f.run(f.input).ok,true);assert.equal(f.run(f.input).ok,true);assert.equal(f.files.size,1);assert.equal([...f.files.values()][0].parents[0],'12gCZmqioYGZyRmgW3CsWyobBBcUnCFUS');assert.equal(f.run({...f.input,company:'GHR'}).error,'FILE_IDENTITY_CONFLICT');assert.equal(f.files.size,1);});
test('corrupt PDF or hash cannot create a file; changed metadata cannot hijack an existing ID',()=>{const f=service();assert.equal(f.run({...f.input,sha256:'b'.repeat(64)}).error,'INVALID_PDF');assert.equal(f.calls(),0);f.run(f.input);assert.equal(f.run({...f.input,name:'different.pdf'}).error,'FILE_IDENTITY_CONFLICT');});
